/**
 * Item catalogue.
 *
 * All names follow the naming school in docs/06-ART-DIRECTION.md: functional,
 * matter-of-fact German with an invented technical suffix. Nothing here is
 * borrowed from an existing game (see docs/00-VISION.md, section 8).
 */

import type { ItemDef } from './types';

export const ITEMS = {
  // ── Weapons (the inventory representation; stats live in weapons.ts) ──────
  itm_wpn_splitter: {
    id: 'itm_wpn_splitter',
    name: 'Splitter VK-2',
    description: 'Kompakte Maschinenpistole. Hohe Feuerrate, geringe Reichweite.',
    category: 'weapon',
    rarity: 'common',
    weight: 2.8,
    value: 640,
    stackSize: 1,
    icon: 'icon.item.wpn_splitter',
  },
  itm_wpn_nadel: {
    id: 'itm_wpn_nadel',
    name: 'Nadel PR-9',
    description: 'Präzisionsgewehr aus Bestand des Kartograph-Ordens. Belohnt ruhige Hände.',
    category: 'weapon',
    rarity: 'rare',
    weight: 4.1,
    value: 2150,
    stackSize: 1,
    icon: 'icon.item.wpn_nadel',
  },
  itm_wpn_bruch: {
    id: 'itm_wpn_bruch',
    name: 'Bruch SG-40',
    description: 'Grobe Schrotwaffe. Auf zwei Meter gibt es keine Diskussion.',
    category: 'weapon',
    rarity: 'uncommon',
    weight: 3.6,
    value: 1280,
    stackSize: 1,
    icon: 'icon.item.wpn_bruch',
  },

  // ── Ammunition ───────────────────────────────────────────────────────────
  // Every calibre has a standard load plus specialists. Which one is chambered
  // changes what a weapon *is*, which is the heart of M2.
  itm_ammo_9mm: {
    id: 'itm_ammo_9mm',
    name: '9 mm Kern',
    description: 'Standardmunition. Überall zu finden, selten genug wenn es zählt.',
    category: 'ammo',
    rarity: 'common',
    weight: 0.012,
    value: 3,
    stackSize: 180,
    icon: 'icon.item.ammo_9mm',
    ammo: {
      caliber: 'cal_9mm',
      damageMultiplier: 1,
      penetration: 18,
      fragmentation: 0.15,
      fragmentationBonus: 0.35,
      speedMultiplier: 1,
    },
  },
  itm_ammo_9mm_ap: {
    id: 'itm_ammo_9mm_ap',
    name: '9 mm Stahlkern',
    description: 'Gehärteter Kern. Geht durch Westen, richtet dahinter weniger an.',
    category: 'ammo',
    rarity: 'rare',
    weight: 0.014,
    value: 14,
    stackSize: 120,
    icon: 'icon.item.ammo_9mm_ap',
    ammo: {
      caliber: 'cal_9mm',
      damageMultiplier: 0.82,
      penetration: 38,
      fragmentation: 0,
      fragmentationBonus: 0,
      speedMultiplier: 1.12,
    },
  },
  itm_ammo_9mm_hp: {
    id: 'itm_ammo_9mm_hp',
    name: '9 mm Splitterkern',
    description: 'Zerlegt sich im Ziel. Gegen Ungepanzerte verheerend, gegen Platten nutzlos.',
    category: 'ammo',
    rarity: 'uncommon',
    weight: 0.012,
    value: 9,
    stackSize: 120,
    icon: 'icon.item.ammo_9mm_hp',
    ammo: {
      caliber: 'cal_9mm',
      damageMultiplier: 1.25,
      penetration: 8,
      fragmentation: 0.55,
      fragmentationBonus: 0.6,
      speedMultiplier: 0.95,
    },
  },

  itm_ammo_74: {
    id: 'itm_ammo_74',
    name: '7,4 Riss',
    description: 'Gehärtete Präzisionsmunition. Durchschlägt leichte Panzerung.',
    category: 'ammo',
    rarity: 'rare',
    weight: 0.019,
    value: 11,
    stackSize: 120,
    icon: 'icon.item.ammo_74',
    ammo: {
      caliber: 'cal_74',
      damageMultiplier: 1,
      penetration: 40,
      fragmentation: 0.2,
      fragmentationBonus: 0.4,
      speedMultiplier: 1,
    },
  },
  itm_ammo_74_ap: {
    id: 'itm_ammo_74_ap',
    name: '7,4 Durchschlag',
    description: 'Wofür Plattenträger nicht gebaut wurden.',
    category: 'ammo',
    rarity: 'epic',
    weight: 0.022,
    value: 34,
    stackSize: 90,
    icon: 'icon.item.ammo_74_ap',
    ammo: {
      caliber: 'cal_74',
      damageMultiplier: 0.9,
      penetration: 62,
      fragmentation: 0,
      fragmentationBonus: 0,
      speedMultiplier: 1.15,
    },
  },

  itm_ammo_12: {
    id: 'itm_ammo_12',
    name: '12er Streu',
    description: 'Schrotpatronen. Laut, brutal, kurzreichweitig.',
    category: 'ammo',
    rarity: 'uncommon',
    weight: 0.045,
    value: 8,
    stackSize: 60,
    icon: 'icon.item.ammo_12',
    ammo: {
      caliber: 'cal_12',
      damageMultiplier: 1,
      penetration: 10,
      fragmentation: 0.3,
      fragmentationBonus: 0.4,
      speedMultiplier: 1,
    },
  },
  itm_ammo_12_slug: {
    id: 'itm_ammo_12_slug',
    name: '12er Vollgeschoss',
    description: 'Ein einziges schweres Projektil. Macht aus der Schrotwaffe ein Gewehr.',
    category: 'ammo',
    rarity: 'rare',
    weight: 0.052,
    value: 22,
    stackSize: 40,
    icon: 'icon.item.ammo_12_slug',
    ammo: {
      caliber: 'cal_12',
      damageMultiplier: 5.2,
      penetration: 34,
      fragmentation: 0.1,
      fragmentationBonus: 0.3,
      speedMultiplier: 1.35,
      pelletsOverride: 1,
      spreadMultiplier: 0.28,
    },
  },

  // ── Medical ──────────────────────────────────────────────────────────────
  itm_bandage: {
    id: 'itm_bandage',
    name: 'Feldverband',
    description: 'Stoppt die Blutung. Mehr nicht.',
    category: 'medical',
    rarity: 'common',
    weight: 0.2,
    value: 45,
    stackSize: 6,
    icon: 'icon.item.bandage',
    consumable: { health: 25, useSeconds: 2.2 },
  },
  itm_medkit: {
    id: 'itm_medkit',
    name: 'Trauma-Kit',
    description: 'Vollständige Wundversorgung. Braucht Zeit, die man selten hat.',
    category: 'medical',
    rarity: 'uncommon',
    weight: 0.9,
    value: 210,
    stackSize: 3,
    icon: 'icon.item.medkit',
    consumable: { health: 65, useSeconds: 4.5 },
  },
  itm_stim: {
    id: 'itm_stim',
    name: 'Echo-Stim',
    description: 'Synthetisiert aus Riss-Rückständen. Der Körper vergisst kurz, dass er müde ist.',
    category: 'medical',
    rarity: 'rare',
    weight: 0.15,
    value: 380,
    stackSize: 4,
    icon: 'icon.item.stim',
    consumable: { health: 15, stamina: 100, useSeconds: 1.2 },
  },

  // ── Armor ────────────────────────────────────────────────────────────────
  itm_armor_fiber: {
    id: 'itm_armor_fiber',
    name: 'Faserweste',
    description: 'Leicht, günstig, hält genau einen Fehler aus.',
    category: 'armor',
    rarity: 'common',
    weight: 3.2,
    value: 420,
    stackSize: 1,
    icon: 'icon.item.armor_fiber',
    armor: {
      armorClass: 2,
      reduction: 0.3,
      durability: 40,
      coverage: ['torso'],
      speedPenalty: 0.02,
    },
  },
  itm_armor_plate: {
    id: 'itm_armor_plate',
    name: 'Plattenträger MK-3',
    description: 'Schwer und teuer. Der Unterschied zwischen Rückweg und Verlustmeldung.',
    category: 'armor',
    rarity: 'epic',
    weight: 8.4,
    value: 3400,
    stackSize: 1,
    icon: 'icon.item.armor_plate',
    armor: {
      armorClass: 4,
      reduction: 0.55,
      durability: 110,
      coverage: ['torso'],
      speedPenalty: 0.08,
    },
  },
  itm_helmet_shell: {
    id: 'itm_helmet_shell',
    name: 'Schalenhelm',
    description: 'Deckt genau die Zone ab, die sonst jeden Raid beendet.',
    category: 'armor',
    rarity: 'rare',
    weight: 2.1,
    value: 1450,
    stackSize: 1,
    icon: 'icon.item.helmet_shell',
    armor: {
      armorClass: 3,
      reduction: 0.42,
      durability: 45,
      coverage: ['head'],
      speedPenalty: 0.01,
    },
  },

  // ── Backpacks ────────────────────────────────────────────────────────────
  itm_bag_small: {
    id: 'itm_bag_small',
    name: 'Umhängetasche',
    description: 'Wenig Platz. Zwingt zu Entscheidungen.',
    category: 'backpack',
    rarity: 'common',
    weight: 0.8,
    value: 180,
    stackSize: 1,
    icon: 'icon.item.bag_small',
    capacityKg: 14,
  },
  itm_bag_medium: {
    id: 'itm_bag_medium',
    name: 'Feldrucksack',
    description: 'Der Standard für ernsthafte Ausflüge in die Risse.',
    category: 'backpack',
    rarity: 'uncommon',
    weight: 1.9,
    value: 760,
    stackSize: 1,
    icon: 'icon.item.bag_medium',
    capacityKg: 24,
  },
  itm_bag_large: {
    id: 'itm_bag_large',
    name: 'Bergungstrage',
    description: 'Nimmt fast alles auf. Macht dich fast unbeweglich.',
    category: 'backpack',
    rarity: 'rare',
    weight: 3.4,
    value: 2400,
    stackSize: 1,
    icon: 'icon.item.bag_large',
    capacityKg: 38,
  },

  // ── Sichere Behälter ─────────────────────────────────────────────────────
  //
  // The single most beloved object in the genre, and the reason a bad raid is
  // survivable: whatever fits in here comes home even when you do not. It is
  // deliberately tiny. A secure container that holds a raid's worth of loot
  // would remove the decision it exists to create.
  itm_case_small: {
    id: 'itm_case_small',
    name: 'Sicherungskassette',
    description: 'Riss-stabilisiert. Was hier drin liegt, kommt zurück - auch ohne dich.',
    category: 'container',
    rarity: 'rare',
    weight: 0.6,
    value: 5200,
    stackSize: 1,
    icon: 'icon.item.case_small',
    capacityKg: 2.5,
  },
  itm_case_large: {
    id: 'itm_case_large',
    name: 'Bergungskassette',
    description: 'Größer, schwerer, und die Fraktionen töten dafür.',
    category: 'container',
    rarity: 'epic',
    weight: 1.4,
    value: 17000,
    stackSize: 1,
    icon: 'icon.item.case_large',
    capacityKg: 5,
  },

  // ── Attachments ──────────────────────────────────────────────────────────
  itm_att_barrel_long: {
    id: 'itm_att_barrel_long',
    name: 'Langlauf VK',
    description: 'Mehr Lauf, mehr Reichweite, mehr Gewicht am Handgelenk.',
    category: 'attachment',
    rarity: 'uncommon',
    weight: 0.9,
    value: 620,
    stackSize: 1,
    icon: 'icon.item.att_barrel',
  },
  itm_att_sight_reflex: {
    id: 'itm_att_sight_reflex',
    name: 'Reflexvisier',
    description: 'Ruhiger Punkt statt Kimme. Der Unterschied auf zwanzig Meter.',
    category: 'attachment',
    rarity: 'uncommon',
    weight: 0.25,
    value: 540,
    stackSize: 1,
    icon: 'icon.item.att_sight',
  },
  itm_att_mag_extended: {
    id: 'itm_att_mag_extended',
    name: 'Erweitertes Magazin',
    description: 'Mehr Schuss vor dem Nachladen — und ein längeres Nachladen.',
    category: 'attachment',
    rarity: 'uncommon',
    weight: 0.35,
    value: 480,
    stackSize: 1,
    icon: 'icon.item.att_mag',
  },
  itm_att_muzzle_suppressor: {
    id: 'itm_att_muzzle_suppressor',
    name: 'Schalldämpfer',
    description: 'Halbiert, wie weit dein Schuss die Aufmerksamkeit trägt.',
    category: 'attachment',
    rarity: 'rare',
    weight: 0.6,
    value: 1650,
    stackSize: 1,
    icon: 'icon.item.att_suppressor',
  },
  itm_att_muzzle_comp: {
    id: 'itm_att_muzzle_comp',
    name: 'Kompensator',
    description: 'Hält die Waffe im Dauerfeuer unten. Laut bleibt sie trotzdem.',
    category: 'attachment',
    rarity: 'uncommon',
    weight: 0.3,
    value: 590,
    stackSize: 1,
    icon: 'icon.item.att_comp',
  },

  // ── Throwables ───────────────────────────────────────────────────────────
  itm_thr_frag: {
    id: 'itm_thr_frag',
    name: 'Splitterladung',
    description: 'Löst Probleme um Ecken herum. Auch deine eigenen.',
    category: 'throwable',
    rarity: 'uncommon',
    weight: 0.45,
    value: 320,
    stackSize: 4,
    icon: 'icon.item.thr_frag',
  },
  itm_thr_flash: {
    id: 'itm_thr_flash',
    name: 'Blender',
    description: 'Nimmt einem Raum für ein paar Sekunden die Augen.',
    category: 'throwable',
    rarity: 'uncommon',
    weight: 0.3,
    value: 280,
    stackSize: 4,
    icon: 'icon.item.thr_flash',
  },
  itm_thr_lure: {
    id: 'itm_thr_lure',
    name: 'Echo-Köder',
    description: 'Erzeugt ein Geräusch, das nach dir klingt. Es klingt nur nicht dort, wo du bist.',
    category: 'throwable',
    rarity: 'rare',
    weight: 0.25,
    value: 460,
    stackSize: 4,
    icon: 'icon.item.thr_lure',
  },

  // ── Keys ─────────────────────────────────────────────────────────────────
  itm_key_vault: {
    id: 'itm_key_vault',
    name: 'Sicherheitsschlüssel',
    description: 'Öffnet eine Sicherheitskammer. Wo die passende steht, sagt er nicht.',
    category: 'key',
    rarity: 'rare',
    weight: 0.05,
    value: 750,
    stackSize: 5,
    icon: 'icon.item.key_vault',
  },

  // ── Materials ────────────────────────────────────────────────────────────
  itm_scrap: {
    id: 'itm_scrap',
    name: 'Metallschrott',
    description: 'Grundstoff für jede Werkbank.',
    category: 'material',
    rarity: 'common',
    weight: 0.35,
    value: 22,
    stackSize: 40,
    icon: 'icon.item.scrap',
  },
  itm_copper: {
    id: 'itm_copper',
    name: 'Kupferwicklung',
    description: 'Aus ausgeschlachteten Motoren. Leitet, was leiten soll.',
    category: 'material',
    rarity: 'common',
    weight: 0.3,
    value: 38,
    stackSize: 30,
    icon: 'icon.item.copper',
  },
  itm_circuit: {
    id: 'itm_circuit',
    name: 'Platinenmodul',
    description: 'Funktionierende Elektronik ist in den Rissen fast schon Währung.',
    category: 'material',
    rarity: 'uncommon',
    weight: 0.18,
    value: 145,
    stackSize: 20,
    icon: 'icon.item.circuit',
  },
  itm_polymer: {
    id: 'itm_polymer',
    name: 'Verbundpolymer',
    description: 'Zäh, leicht, in dieser Reinheit nicht mehr herstellbar.',
    category: 'material',
    rarity: 'uncommon',
    weight: 0.22,
    value: 165,
    stackSize: 20,
    icon: 'icon.item.polymer',
  },

  // ── Valuables ────────────────────────────────────────────────────────────
  itm_echoshard: {
    id: 'itm_echoshard',
    name: 'Echo-Splitter',
    description: 'Ein Stück gefrorene Riss-Energie. Selbst der Tod nimmt dir nicht alle davon.',
    category: 'valuable',
    rarity: 'rare',
    weight: 0.05,
    value: 500,
    stackSize: 50,
    icon: 'icon.item.echoshard',
  },
  itm_datacore: {
    id: 'itm_datacore',
    name: 'Forschungsdaten',
    description: 'Aufzeichnungen von Menschen, die den Rissen zu nahe kamen.',
    category: 'valuable',
    rarity: 'epic',
    weight: 0.4,
    value: 1750,
    stackSize: 8,
    icon: 'icon.item.datacore',
  },
  itm_risscore: {
    id: 'itm_risscore',
    name: 'Riss-Kern',
    description: 'Der Puls eines Echo-Risses, eingeschlossen. Er ist warm. Er sollte es nicht sein.',
    category: 'valuable',
    rarity: 'legendary',
    weight: 1.6,
    value: 8500,
    stackSize: 3,
    icon: 'icon.item.risscore',
  },
} as const satisfies Record<string, ItemDef>;

export type ItemId = keyof typeof ITEMS;

export function getItem(id: ItemId): ItemDef {
  return ITEMS[id];
}

/** Runtime-safe lookup for data coming from a save file. */
export function findItem(id: string): ItemDef | undefined {
  return (ITEMS as Record<string, ItemDef>)[id];
}

export function isItemId(id: string): id is ItemId {
  return id in ITEMS;
}

export const ALL_ITEM_IDS = Object.keys(ITEMS) as ItemId[];
